### ISSUE TITLE
Is there a concept of private and public CGPM?

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/cgpm#177]
I have been using `View` as a `DP Mixture` CGPM, but I have the feeling that this was not its intended use case. Instead, it seems that `View` (and `Dim` and `Importance`) is a private CGPM, that is necessary for public CGPMs, such as `State`, but should not be used independently.

A solution would then be to implement a public `DP Mixture` CGPM (basically a `State` with one view), which is on the top level, that is, it is not used in other CGPM's, but it is exposed to the user.

**Comment by fsaad** [comment]
This is a great question. What you are observing in `State` appearing as a "public CGPM" and `View` as a "private CGPM" is mostly an artifact of (i) the history of how the software developed, and (ii) the different forms of "composition" that CGPMs aim to support.

What do we mean by "composable generative population models"? There are really two forms of composition in the cgpm-library, only one of which we have treated formally in the technical report on the arXiv:

1. __Flat composition__: Building a directed acyclic network of CGPMs, where they are composed via applying input/output application.

2. __Nested composition__: Building a CGPMs compositionally out of primitive CGPMs and "meta-combinator" CGPMs. This composition is how `State` is implemented, all of its internal components (`View`, `Dim`, `Crp`, and `DistributionCgpm`) are themselves implemented as CGPMs.

Flat composition is mostly straightforward to implement; compositional algorithms of `simulate/logpdf` follow from importance sampling in a "generalized" directed graph, where the nodes are CGPMs.

Nested composition is much less straightforward. Treating CGPMs directly as software comes with challenging questions about:

-  How to coordinate things like data-structures, error checking, observation-storage, and method implementations (i.e. `incorporate`, `simulate`, and `logpdf`) among the nested CGPMs.

- The minimal interface that suffices for "nested" composition. As it stands, the formalism of `simulate/logpdf` and `cgpm.inputs` and `cgpm.outputs` provides a uniform treatment for many operations (in particular, the importance network is used for both flat and nested composition, albeit in very different ways). There are still rough edges, however, for drawing out the abstraction boundaries for other programmatic operations that CGPMs need to perform on their "nested" children.

Where does this leave us? Probably with a future computer science MEng thesis carefully defining nested composition. I am quite excited about what we will find, because the nested-composition project in my opinion is more relevant to "probabilistic programming" than flat-composition. Formal semantics for object composition is a classical problem in computer science and software engineering, and there is much to be drawn from that field to define ADTs (for example) for probabilistic modules.

**Comment by marcoct** [comment]
The 'probabilistic modules' interface can support recursive composition that preserves the invariants under composition (although this has not been demonstrated yet). It is a less stringent interface than CGPMs, as it does not require the log-density, but instead a stochastic generalization of the log-density.

**Comment by fsaad** [comment]
That's interesting. I agree that the mathematical interface of "probabilistic modules" might provide a formal treatment for nested compositions. I think that @leocasarsa is also picking up  difficulty with respect to the software engineering aspect of nested composition; often times for probabilistic inference, we need to perform operations (i.e. mutating data structures) which cross abstraction boundaries specified by `simulate/logpdf` or `simulate/regenerate`.
